dist: trusty

os:
- linux

language: go

go:
- 1.8

before_install:
- go get -u github.com/alecthomas/gometalinter

install:
- gometalinter --install

script:
- travis_wait 20 goveralls -service=travis-ci