dist: trusty

os:
- linux

language: go

go:
- 1.8

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

before_install:
- go get github.com/mattn/goveralls

install:
- glide install

script:
- travis_wait 20 goveralls -service=travis-ci